dependencies:
  - name: postgresql
    repository: https://charts.containerum.io
    version: 0.15.0
    tags:
      - db
      - postgresql
      - platform
  - name: mongodb
    version: "3.0.4"
    repository: https://charts.containerum.io
    tags:
      - db
      - mongo
      - platform
  - name: api-gateway
    version: "v1.0.3-rc.1"
    repository: https://charts.containerum.io
    tags:
      - back
      - gateway
      - platform
  - name: user-manager
    version: "v1.0.3-rc.0"
    repository: https://charts.containerum.io
    tags:
      - back
      - user
      - platform
  - name: resource
    version: "v1.0.3-rc.3"
    repository: https://charts.containerum.io
    tags:
      - back
      - resource
      - platform
  - name: permissions
    version: "v1.0.2-rc.5"
    repository: https://charts.containerum.io
    tags:
      - back
      - permissions
      - platform
  - name: kube
    version: "v1.0.5-rc.0"
    repository: https://charts.containerum.io
    tags:
      - back
      - kube
      - platform
  - name: auth
    version: "v1.0.2-rc.0"
    repository: https://charts.containerum.io
    tags:
      - back
      - auth
      - platform
  - name: mail
    version: "v1.0.1-rc.0"
    repository: https://charts.containerum.io
    tags:
      - back
      - mail
      - platform
  - name: ui
    version: "v1.0.4-rc.0"
    repository: https://charts.containerum.io
    tags:
      - front
      - ui
      - platform
