tags:
  db: false
  platform: false
  platformdb: true
  postgresql: true
  mongo: true
  mail: true
  user: true
  permissions: true
  resource: true
  kube: true
  gateway: true

ingress:
  ui:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - example.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  api:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - api.example.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


mail:
  persistence:
    enabled: false

user-manager:
  tags:
    platformdb: true
  env:
    global:
      CH_USER_PG_DBNAME: containerum
      CH_USER_PG_LOGIN: postgres
    local:
      CH_USER_PG_ADDR: null

permissions:
  tags:
    platformdb: true
  env:
    global:
      DB_BASE: containerum
      DB_USER: postgres
    local:
      DB_HOST: null

resource:
  tags:
    platformdb: true
  env:
    global:
      CH_RESOURCE_MONGO_DB: containerum
      CH_RESOURCE_MONGO_LOGIN: mongo
    local:
      CH_RESOURCE_MONGO_ADDR: null

api-gateway:
  env:
    local:
      SERVICE_HOST_PREFIX: release-name
      GRPC_AUTH_ADDRESS: null

postgresql:
  persistence:
    enabled: false
  postgresDatabase: containerum
  # postgresUser: postgres
  # postgresPassword: password


mongodb:
  persistence:
    enabled: false
  mongodbDatabase: containerum
  mongodbUsername: mongo
  # mongodbPassword: password
