
required = ["github.com/UnnoTed/fileb0x"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "k8s.io/helm"
  version = "~v2.9.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  name = "github.com/mholt/archiver"
  revision = "089cf0d1f58c48b3d14c76882a37708efe549e7b"

[[constraint]]
  name = "github.com/UnnoTed/fileb0x"
  version = "~v1.0.0"
  #revision = "279e1dc62738d19a9106f401539c0e9b4d4ff477"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "~2.2.1"

[[constraint]]
  name = "github.com/octago/sflags"
  version = "~0.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~v1.0.6"

[[constraint]]
  name = "github.com/go-playground/validator"
  version = "~9.21.0"

[[constraint]]
  name = "github.com/ericchiang/k8s"
  version = "~v1.2.0"

[[constraint]]
  name = "github.com/thoas/go-funk"
  revision = "1060394a7713649853efcb78f5c929b877efbbbb"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "~v1.13.7"


[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/zyedidia/micro"
  version = "~1.4.1"

[[constraint]]
  name = "github.com/huandu/xstrings"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/common-nighthawk/go-figure"
  revision = "18b2b544842cab16f3ff418fb5290d8f2896a069"

#####################################


#[[override]]
#  name = "k8s.io/kubernetes
#  version = "~1.9.3"

#[[override]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.9.3"

#[[override]]
#  name = "github.com/docker/docker"
#  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

#[[override]]
#  name = "github.com/russross/blackfriday"
#  version = "~v1.4-2-g300106c"
